### ISSUE TITLE
Problem accessing pipermail/ on the gobolinux homepage

### ISSUE THREAD

**Issue by ghost** [gobolinux/gobolinux.org#2]
Heya, two things, one small, one medium:

**(1)**

The link on the homepage points to:

"http://lists.gobolinux.org//pipermail/gobolinux-users/"

I believe one / is too much there and it should instead be:

"http://lists.gobolinux.org/pipermail/gobolinux-users/"

**(2)**

The bigger issue though:

When I click on the link above, I get this error:

    Forbidden

    You don't have permission to access /pipermail/gobolinux-users/ on this server.
    Apache/2.4.10 (Debian) Server at lists.gobolinux.org Port 80"

I assume that the mailing list has been relocated? If I recall correctly so
then it was somewhere else in the past but I am unsure.

Anyway, it may be that this is known and will be fixed anyway, just in
the case that (2) is not known, better to report twice than none. Thanks!

**Comment by mwh** [comment]
I've fixed the server configuration issue that denied access to the archives, so they are readable again now. I've also fixed the link on the home page.
