### ISSUE TITLE
older_docs/differences.html needs attention

### ISSUE THREAD

**Issue by bolangi** [gobolinux/gobolinux.org#5]
This is a very concise introduction to Gobo. However some updates are needed:  there is some fat to trim, change paths from /System/Links  to /System/Index, and general editing for clarity. This ticket will be closed with an improved version of the article, moving it to a current articles directory, and updating top-level link(s) to this article.

**Comment by hishamhm** [comment]
differences.html is quite redundant now, compared to at_a_glance. I think we should just remove it.

**Comment by bolangi** [comment]
On Mon, Apr 10, 2017 at 07:08:53PM -0700, Hisham Muhammad wrote:
> differences.html is quite redundant now, compared to at_a_glance. I think we should just remove it.
 
That's fine. 

-- 
Joel Roth

**Comment by bolangi** [comment]
As per the discussion above, I'm closing this issue. For reference, the revised article appears here: https://github.com/gobolinux/Documentation/wiki/What-makes-GoboLinux-unique%3F
