### ISSUE TITLE
Remove old news from lang/en_US/news/

### ISSUE THREAD

**Issue by bolangi** [gobolinux/gobolinux.org#9]
There are 113 news items. I think news releases could be removed before a cutoff date such as 2015.1.1 or the release of 015, if there can be general agreement that those pages are no longer useful.

**Comment by hishamhm** [comment]
And kill the history of the project? We've been careful to keep this data around for over a decade. Also, when I redesigned the site I took care to make sure that the "permalink" links for each news item continue to work (they're meant to be _permanent_ as the name implies).

It's normal for some pages to change, but the news reel in particular is a record of the history of the project.

Related: https://twitter.com/worrydream/status/478087637031325697
